project:
  type: website
  output-dir: docs

website:
  title: "David Garcia Callejas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

editor: visual
